name: Release Drafter

on:
  push:
    tags:
      - v*

permissions: write-all

env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Setup MTK Certification
        uses: https://gitea.mediatek.inc/actions/mtk-cert-action@v1.2.0

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release Drafter
        uses: https://gitea.mediatek.inc/DS906659/release-action@v1.0.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          emoji: true
          capitalize: true
          contributors: true
          dry: false
