name: testing

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  run_tests_gitea:
    if: ${{ contains(github.server_url, 'gitea') }}
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-20.04  # Uncomment it if you use it on Gitea

    env:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
      GOPROXY: http://oa-mirror.mediatek.inc/repository/golang

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Test
        run: |
          make test

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            .github/reports/coverage.out
            .github/reports/coverage.html
            .github/reports/test-results.xml

      - name: Coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        with:
          pytest-coverage-path: ./.github/reports/coverage.html
          junitxml-path: ./.github/reports/test-results.xml
          # Note: There is a known issue possibly due to API differences between Gitea and GitHub
          # report-only-changed-files: true
          title: Coverage
          remove-link-from-badge: true
          junitxml-title: Coverage Summary 👮

  run_tests_github:
    if: ${{ contains(github.server_url, 'github') }}
    runs-on: ubuntu-latest

    steps:
      - name: Disable SSL Verify
        run: git config --global http.sslVerify false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Test
        run: |
          make test

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            .github/reports/coverage.out
            .github/reports/coverage.html
            .github/reports/test-results.xml

      - name: Coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: 0
        with:
          pytest-coverage-path: ./.github/reports/coverage.html
          junitxml-path: ./.github/reports/test-results.xml
          # Note: There is a known issue possibly due to API differences between Gitea and GitHub
          # report-only-changed-files: true
          title: Coverage
          remove-link-from-badge: true
          junitxml-title: Coverage Summary 👮
